moderate_discussion:
  description: >
    Provide guidance or feedback to keep the debate on track.
  expected_output: >
    A statement or action that helps maintain the flow and fairness of the debate.
  agent: moderator_agent
