evaluate_response:
  description: >
    Evaluate the response "{response}" from {debater_name} to ensure it matches their style.
    Provide your evaluation in the following JSON format, and ensure it's properly formatted:

    {{
      "is_valid": true or false,
      "feedback": "Your feedback here"
    }}
  expected_output: >
    {{
      "is_valid": true or false,
      "feedback": "Your feedback here"
    }}
  agent: evaluator_agent
